import type { Metadata } from 'next';
import { GeistSans as geist } from 'geist/font/sans';
import '../styles/global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={geist.className}>{children}</body>
    </html>
  );
}
